exports.MigrationDelegatesNames = {
  SCOPED_SLOTS: 'SCOPED_SLOTS',
  ADD_EMITS: 'ADD_EMITS',
  REMOVE_EMITS: 'REMOVE_EMITS',
  TRANSLATIONS: 'TRANSLATIONS',
  EVENT_NATIVE_MODIFIER: 'EVENT_NATIVE_MODIFIER',
  ATTRIBUTE_SYNC: 'ATTRIBUTE_SYNC',
  LIFECYCLE_HOOKS: 'LIFECYCLE_HOOKS',
  UID: 'UID',
};
